### ISSUE TITLE
Format annotation file 

### ISSUE THREAD

**Issue by arnovaill** [penny4860/SVHN-deep-digit-detector#43]
I tried to load the data thanks to "1_sample_loader.py" which requires a digitStruct.json file. Inside the  train.tar.gz file there is only a digitStruct.mat file. Have you done any manipulation to convert it in matlab from .mat to .json ?

**Comment by penny4860** [comment]
You can use https://github.com/penny4860/SVHN-deep-digit-detector/blob/master/annotation/train/digitStruct.json and https://github.com/penny4860/SVHN-deep-digit-detector/blob/master/annotation/test/digitStruct.json
